name: Deploy ProjectHive with Docker Compose

on:
  push:
    branches:
      - Deploy   # Change to your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Pre-Build Cleanup
        run: |
          echo "Pruning unused Docker resources before build..."
          docker-compose down --remove-orphans --volumes || true
          docker container rm -f springboot || true
          docker container rm -f react-frontend || true
          docker container rm -f mysql || true
          docker system prune -f --volumes || true

      - name: Build and Deploy Docker Containers
        run: |
          echo "Building and starting Docker containers..."
          docker-compose build --no-cache
          docker-compose up -d

      - name: Show Running Containers
        if: always()
        run: docker-compose ps
